name: PR Notification
on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Olá equipa! Foi aberto um novo Pull Request. Por favor, revejam o código documentado com Javadoc.'
            })
